{% set name = "croniter" %}
{% set version = "1.3.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "dbf02070988abc7e8955583915931b36f865c38289390be11a0c4112b55caac6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - wheel
    - setuptools

  run:
    - python
    - python-dateutil

test:
  imports:
    - croniter.croniter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/kiorky/croniter
  license: MIT
  license_family: MIT
  summary: 'croniter provides iteration for datetime object with cron like format'
  dev_url: https://github.com/kiorky/croniter
  doc_url: https://github.com/kiorky/croniter#readme

extra:
  recipe-maintainers:
    - pmlandwehr
    - mariusvniekerk
