{% set name = "croniter" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34117ec1741f10a7bd0ec3ad7d8f0eb8fa457a2feb9be32e6a2250e158957668

build:
  number: 0
  skip: True  # [py<38]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools

  run:
    - python
    - python-dateutil

test:
  imports:
    - croniter
    - croniter.croniter
  requires:
    - pip
    - pytz
  commands:
    - pip check

about:
  home: https://github.com/kiorky/croniter
  license: MIT
  license_family: MIT
  license_url: https://github.com/kiorky/croniter/blob/master/docs/LICENSE
  license_file: LICENSE
  summary: 'croniter provides iteration for datetime object with cron like format'
  description: "croniter provides iteration for the datetime object with a cron like format."
  dev_url: https://github.com/kiorky/croniter
  doc_url: https://github.com/kiorky/croniter#readme
  doc_source_url: https://github.com/kiorky/croniter#readme

extra:
  recipe-maintainers:
    - pmlandwehr
    - mariusvniekerk
