{% set name = "croniter" %}
{% set version = "0.3.22" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "4f8e828fab4bf5918b4c2e990b6a8f9d653557ae7f1f38bebed63bcfe1858a45" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  preserve_egg_dir: True
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-dateutil

test:
  imports:
    - croniter
    - croniter.tests

about:
  home: https://github.com/kiorky/croniter
  license: MIT
  license_family: MIT
  summary: 'croniter provides iteration for datetime object with cron like format'
  dev_url: https://github.com/kiorky/croniter

extra:
  recipe-maintainers:
    - pmlandwehr
