{% set name = "croniter" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37c504b313956114a983ece2c2b07790b1f1094fe9d81cc94739214748255577

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - python-dateutil
    - pytz >2021.1

test:
  source_files:
    - src/croniter
  imports:
    - croniter
    - croniter.croniter
  commands:
    - pip check
    # pyargs not work tests folder excluded from the site_pkg dir
    - pytest -v src/croniter
  requires:
    - pip
    - pytest >=8.3.3

about:
  home: https://github.com/kiorky/croniter
  license: MIT
  license_family: MIT
  license_url: https://github.com/kiorky/croniter/blob/master/LICENSE
  summary: 'croniter provides iteration for datetime object with cron like format'
  description: "croniter provides iteration for the datetime object with a cron like format."
  dev_url: https://github.com/kiorky/croniter
  doc_url: https://github.com/kiorky/croniter#readme

extra:
  recipe-maintainers:
    - pmlandwehr
    - mariusvniekerk
