{% set name = "croniter" %}
{% set version = "1.0.13" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "57f36df4f5a1c31bbf50bbffa3551612c19f6156ab1e88e2e42342ccbb9f9b9a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - python-dateutil
    - natsort
    - future

test:
  imports:
    - croniter.croniter

about:
  home: https://github.com/kiorky/croniter
  license: MIT
  license_family: MIT
  summary: 'croniter provides iteration for datetime object with cron like format'
  dev_url: https://github.com/kiorky/croniter

extra:
  recipe-maintainers:
    - pmlandwehr
    - mariusvniekerk
