# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fyIio1aS3zTT2AUFEKKcbIY5TqY+xTxCO/qkDmzBXjtlG68beDTscCASeXFpvygYhGVAJ6MQdsVILNZwrRs9N3mZG1/2T0DAFwsOnERjxybEGP5yFRJDs1VDb12CBn87nvNvCl79ZTG7MndgrEApBTdQbF+h2bKNNGl0nSM4td2dDpZjO0Mj+u27XEyoVzcCF8Lx3dvl7m5gceW1unNu82vJ2T4IhukOgs7cz4/SLdimiPSjOBmSdlBQLSpA8TA/lXSuola0OBjK+WzkJryzyvl0KOKAjIT+4AQN8hAZvzPNHO807td7FdFGHzh3CxqW5wmLszetcv0io6ywoeZ/8InashWXWCl+s/n6fyiFs0N3a6A67lj7upBV3CFCPVoScKvsjDPVtBfo54hg9BdBWl0wPVRc3cKDDoJgiLhQitsK1KPaUWoN0FwWm8fP+4QNEVAHE+zcRtsLHq49lSYTkBCfECMRVPewlYUVSw9NdjU5C0QpMcuhl8PnTLTYry/VnJcVtZpmQlDpJ+AZxOcb9S1JnKn1AcvOMhuhBqyb6GxQdM3yPUJ9RPvTY5sbB3gA7c/lrAkjWrYxcDjctJLeLOyafG3s9577BrnxYbiOohvAofkfuB/sluRGYl+HyqjeLmGi7i9ea8D0w35eyeajuyN+7Zpv+K+bCvm5BYJYK8k="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
