travis:
  secure:
    BINSTAR_TOKEN: fyIio1aS3zTT2AUFEKKcbIY5TqY+xTxCO/qkDmzBXjtlG68beDTscCASeXFpvygYhGVAJ6MQdsVILNZwrRs9N3mZG1/2T0DAFwsOnERjxybEGP5yFRJDs1VDb12CBn87nvNvCl79ZTG7MndgrEApBTdQbF+h2bKNNGl0nSM4td2dDpZjO0Mj+u27XEyoVzcCF8Lx3dvl7m5gceW1unNu82vJ2T4IhukOgs7cz4/SLdimiPSjOBmSdlBQLSpA8TA/lXSuola0OBjK+WzkJryzyvl0KOKAjIT+4AQN8hAZvzPNHO807td7FdFGHzh3CxqW5wmLszetcv0io6ywoeZ/8InashWXWCl+s/n6fyiFs0N3a6A67lj7upBV3CFCPVoScKvsjDPVtBfo54hg9BdBWl0wPVRc3cKDDoJgiLhQitsK1KPaUWoN0FwWm8fP+4QNEVAHE+zcRtsLHq49lSYTkBCfECMRVPewlYUVSw9NdjU5C0QpMcuhl8PnTLTYry/VnJcVtZpmQlDpJ+AZxOcb9S1JnKn1AcvOMhuhBqyb6GxQdM3yPUJ9RPvTY5sbB3gA7c/lrAkjWrYxcDjctJLeLOyafG3s9577BrnxYbiOohvAofkfuB/sluRGYl+HyqjeLmGi7i9ea8D0w35eyeajuyN+7Zpv+K+bCvm5BYJYK8k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
