travis:
  secure:
    BINSTAR_TOKEN: dXcffQ7x/R8q+NhYLd8jOmGRNw/y0f4m7oVnU1AE8rSZj5t8U7vTK9w3vDosKp/B9yLfL7E+RbcUusmAZV5/cPgO+H2KxlF15LVfs4RjRPBFVHzi00gnQxCGsCtgVAS5EYemo+2FxIkhs5J3ir/kkpYGs8FO5NWi4wwJ5qZGuwRwHfgQ58L63MHlcVRHl1y5pTIunK1S9cHMdCxaGcAxe67/7l08cOcH1fxYcM3doO+irxHFYqSOPLCslCckbLvBaNMZChWLhSPsTQzXN5WzM05NyRHWcOyFNHs79dW0eJlUxMSZqvfV7mf+MzqskT6dQPdn5fa1vb3pLHALaNY+VRgRqaaSbrQ5GO0O+XNAuxwPVrEdIY9FqrX2KJCLVBfqWRYZFEgCEecE67Le45TkYe6dmVIFSk2U68h1gz6HgNfhER+pmro9FDa4aZ8iCrg0236idLs0ghN+geQlm9/598/Jb2R1Meap5+dEgakdottsxX0AEZmIKLU4IGZw9Ke5m4vxijC7sa8PCPNwRzse10aVId0vtcHncsCnc8bKACxXauNi7gX7gU4j+ssx4Gaqq9ZXaTo7e5X0yQDEBg5bvP/qVVTlFLRkUSi18XR9LIhvpHGszhJzmTwS0zaAkQ3OqjaGsC+7OhIhDNOP+MzrL8QA4qMBJOk3dTqoq+itXLI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
