travis:
  secure:
    BINSTAR_TOKEN: mUoyE6CmKtaT28IX3UgcyFZLSi/FjDfmsUTd/RoTPDnwGd7oS1yhN5B+qo7KS5vfBVpizgHevPeJ62y91GcsevU/5A+BJYKi+F4DUkZNvC1HjL1KEyAQ2kC/TtxBz057vulUhDbbffHjBxMmh3wpSFSEtN901MxIBdxEassrInPH3pzjHPekYXnW/qC81bw+8Fcr52Nx8LTXe0MGNxBEJcoAeEYOlAPILc2cqKD5xveQOIv14hkIOW7ioaIiLFSpI75POYAHsR2Ewmda10DG5VLhZr/MRhgduH6UjKcuHrp9V5iVPikTwOw2uJZSkJVa2Op8WochRX64JukReLL7pazCqpB3uIra/DOTIqmKEXkDHv5t1ARkieOnl/9FnvZoPGaLYI4wlqFDRmCEH+mldxkOjLHGC7O26NUQRjg72inGjSRGduaNHNgBHdVwLBU/atHkOXA3/he/yVlM2U4E/EH/z+H+IKMOpP6hX02H2iu07xyUHID2VZQPZ6A6KIVhIXDxM1GhUV5aKXV/gaveXo/8MOJ13i1wTM9OyFfdUX3//MC9QMSXNWrzTX46UHsh6QwouN6zc9JcXB4Z3QmaElpNk0TdImdYDx/SRjVCWAC1ygXFMs3a5G/m+GWfDECemHl3G7lORsIFu9u7EGnGYhXtVNdKeYTw7+FVK2HfSOE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
