travis:
  secure:
    BINSTAR_TOKEN: fkcyhzSe2M0EkmUJTfGvfdr4zzUlpwUk3weRfomhvxmtaXvge2G6iaONjhpdD9b48xkY0eBVZ/+tAUgb9TiyBD5yH6vw4M080eJ2eLWVUS5CF3+PfmqtmfJxbc7huELvwc5p42h0gIMrT5lOjJSW1z2wBouzgmvFj4xO3qJGlh8bwGfodacFh3c+KofrAdbABa2/JpEgKHOkrIFNlvKdRmWVIn5Zu+iR+43AyUDf3iRNLr/qxhmSqjn6nGxMvosv0fDFDXOKOsGRxOoT7swDl6q33R19MOoLx09Mw8EQVUATXKgZk9KBum8o4jx+2FwrtiTRPqjXmsN8iAdJHttwsnHsx2UKCvtmMWqcBWFfR6uLuGeZqaqmps0L8P8/RpOe+LBTeTyWAstsRHYSaQD6dzc+QNlZEckIBIkH/yNFu7tGhH5O9jM7xacO0FDzRA27b0S0qscjaAz5ZXfwNFBlWZoP6Y1uQgbeBi44258+DfCbIbaXe7Fe7assMyjqJCoWrO0oVCeR8ARcaX92bEp2ilWk/r8IabSV6NFF+owKw2Bv5eOcl0seR02BiQtg9l7PV4xW2cpC3wGNhpPSNG8sCKI1gnoEApqUdaiLYB9PmHZnqenK1sAM+RiAoCdMAu7WlAR0wN1CnrLmW/IkdWbSUiaX+7PPE07SVG+cBizbJBE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
